Issue #SB-0000 fix: Added code to get video duration
project-sunbird/sunbird-video-player pull request #111
Opened 2022-07-20 12:04 UTC by Xitija

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-20 12:07 UTC, Xitija commented
@HarishGangula 
Sir I am sending this change for getting duration of the video.

cc: @vinukumar-vs @itsvick

2022-07-26 08:17 UTC, vinukumar-vs requested changes

2022-07-26 08:17 UTC, vinukumar-vs commented on projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
> +        if (this.totalDuration === 0 && data.type === 'durationchange') {
This is the generic method to dispatch all the events. This logic should not be present here. 

As discussed, of you need only duration verify the root where we are sending the duration & fix that code if you have any issue.

2022-07-26 11:32 UTC, HarishGangula commented
@Xitija  Test cases are missing for this PR
cc: @vinukumar-vs

2022-07-27 12:36 UTC, Xitija commented
> @Xitija Test cases are missing for this PR cc: @vinukumar-vs

Adding test cases

2022-07-28 05:15 UTC, merged